language: node_js
node_js:
  - 4.2.1
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install -g bower
  - bower install
  - gulp serve &
  - npm install -g protractor
  - webdriver-manager update
sudo: false
